let btnAdd = require('./Add')
let btnSubtract = require('./Subtract')
let btnMultiply = require('./Multiply')
let btnDivide = require('./Divide')

console.log(btnAdd(4,3))
console.log(btnSubtract(4,3))
console.log(btnMultiply(4,3))
console.log(btnMultiply(4,0))
console.log(btnDivide(4,3))
console.log(btnDivide(4,0))